# NUMPY ARRAYS
## CREATING NUMPY ARRAYS

In [1]:
import numpy as np

In [2]:
x = np.array([0, 1, 2, 3, 4])
print('x: ', x)
print('x dimensions: ', x.ndim)
print('x type: ', type(x))
print('x element types: ', x.dtype)

x:  [0 1 2 3 4]
x dimensions:  1
x type:  <class 'numpy.ndarray'>
x element types:  int32


In [3]:
y = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
print('y:\n', y)
print('y dimensions: ', y.ndim)
print('y shape: ', y.shape)
print('y has a total of ', y.size, ' elements')
print('y type: ', type(y))
print('y element types: ', y.dtype)

y:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
y dimensions:  2
y shape:  (4, 3)
y has a total of  12  elements
y type:  <class 'numpy.ndarray'>
y element types:  int32


Create array specifying the datatype (dtype) of the elements

In [4]:
x = np.array([0, 1, 2, 3, 4], dtype = np.float64)
print('x: ', x)
print('The elements in x are of type: ', x.dtype)

x:  [0. 1. 2. 3. 4.]
The elements in x are of type:  float64


Save a NumPy array to a file.

In [5]:
np.save('my_array', y)

Load saved array from current directory

In [6]:
z = np.load('my_array.npy')
print('\nz =\n', z, '\n')
print('z is an object of type: ', type(z))
print('The elements in z are type: ', z.dtype)


z =
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

z is an object of type:  <class 'numpy.ndarray'>
The elements in z are type:  int32


## MULTI-DIMENSIONAL ARRAYS IN NUMPY
Indexing arrays in numpy [NUM_ROWS][NUM_COLUMNS]

In [7]:
a = np.zeros((3,4))
print('a =\n', a)
print('a has shape: ', a.shape)
print('a is an object of type:', type(x))
print('The elements in a are of type:', a.dtype)

a =
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
a has shape:  (3, 4)
a is an object of type: <class 'numpy.ndarray'>
The elements in a are of type: float64


In [8]:
a = np.ones((5,2), dtype = np.int64)
print('a =\n', a)
print('a has shape: ', a.shape)
print('a is an object of type:', type(x))
print('The elements in a are of type:', a.dtype)

a =
 [[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
a has shape:  (5, 2)
a is an object of type: <class 'numpy.ndarray'>
The elements in a are of type: int64


In [9]:
a = np.full((2,3), 10)
print('a =\n', a)
print('a has shape: ', a.shape)
print('a is an object of type:', type(x))
print('The elements in a are of type:', a.dtype)

a =
 [[10 10 10]
 [10 10 10]]
a has shape:  (2, 3)
a is an object of type: <class 'numpy.ndarray'>
The elements in a are of type: int32


In [10]:
a = np.eye(7)
print('a =\n', a)
print('a has shape: ', a.shape)
print('a is an object of type:', type(x))
print('The elements in a are of type:', a.dtype)

a =
 [[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
a has shape:  (7, 7)
a is an object of type: <class 'numpy.ndarray'>
The elements in a are of type: float64


In [11]:
a = np.diag([0, 1, 2, 3, 4])
print('a =\n', a)
print('a has shape: ', a.shape)
print('a is an object of type:', type(x))
print('The elements in a are of type:', a.dtype)

a =
 [[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]]
a has shape:  (5, 5)
a is an object of type: <class 'numpy.ndarray'>
The elements in a are of type: int32


### ARANGE
numpy.arange([start, ]stop, [step, ]dtype=None)

In [12]:
a = np.arange(10)
print('a =\n', a)
print('a has shape: ', a.shape)
print('a is an object of type:', type(x))
print('The elements in a are of type:', a.dtype)

a =
 [0 1 2 3 4 5 6 7 8 9]
a has shape:  (10,)
a is an object of type: <class 'numpy.ndarray'>
The elements in a are of type: int32


In [13]:
a = np.arange(1, 9)
print('a =\n', a)
print('a has shape: ', a.shape)
print('a is an object of type:', type(x))
print('The elements in a are of type:', a.dtype)

a =
 [1 2 3 4 5 6 7 8]
a has shape:  (8,)
a is an object of type: <class 'numpy.ndarray'>
The elements in a are of type: int32


In [14]:
a = np.arange(1, 14, 3)
print('a =\n', a)
print('a has shape: ', a.shape)
print('a is an object of type:', type(x))
print('The elements in a are of type:', a.dtype)

a =
 [ 1  4  7 10 13]
a has shape:  (5,)
a is an object of type: <class 'numpy.ndarray'>
The elements in a are of type: int32


### LINSPACE
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

In [15]:
a = np.linspace(0, 25, 10)
print('a =\n', a)
print('a has shape: ', a.shape)
print('a is an object of type:', type(x))
print('The elements in a are of type:', a.dtype)

a =
 [ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]
a has shape:  (10,)
a is an object of type: <class 'numpy.ndarray'>
The elements in a are of type: float64


In [16]:
a = np.linspace(0, 25, 10, endpoint = False)
print('a =\n', a)
print('a has shape: ', a.shape)
print('a is an object of type:', type(x))
print('The elements in a are of type:', a.dtype)

a =
 [ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]
a has shape:  (10,)
a is an object of type: <class 'numpy.ndarray'>
The elements in a are of type: float64


### RESHAPE
numpy.reshape(array, newshape, order='C')[source]

In [17]:
a = np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [18]:
a = np.reshape(a, [4,5])
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [19]:
a = np.reshape(a, [10, 2])
print(a)
print('a has shape: ', a.shape)
print('a is an object of type:', type(x))
print('The elements in a are of type:', a.dtype)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
a has shape:  (10, 2)
a is an object of type: <class 'numpy.ndarray'>
The elements in a are of type: int32


In [20]:
a = np.diag(np.arange(0, 10, 2))
print(a)

[[0 0 0 0 0]
 [0 2 0 0 0]
 [0 0 4 0 0]
 [0 0 0 6 0]
 [0 0 0 0 8]]


## NUMPY RANDOM FUNCTIONS

In [21]:
a = np.random.random((4, 6))
print(a)

[[0.83089283 0.05292536 0.22834897 0.36019342 0.11649259 0.28717354]
 [0.85918285 0.0696549  0.06027752 0.14446143 0.967476   0.58537113]
 [0.65360169 0.80867249 0.47297977 0.96517183 0.5987538  0.63082705]
 [0.34910055 0.64075361 0.75364438 0.69862544 0.09566628 0.08770779]]


In [22]:
a = np.random.randint(1, 9, size=(2, 10))
print(a)

[[7 3 8 2 4 3 5 1 7 7]
 [7 6 1 1 2 1 1 5 5 4]]


In [23]:
a = np.random.normal(0, .5, size = (100, 100))
print(a)
print('Size: ', a.size)
print('Mean: ', a.mean())
print('Maximum value: ', a.max())
print('Minimum value: ', a.min())
print('Positive numbers: ', (a > 0).sum())
print('Negative numbers: ', (a < 0).sum())

[[ 0.68207399  0.10321441  0.27347161 ... -0.57221744  0.04932712
   0.48432056]
 [-0.00960367 -0.35447498  0.10466994 ... -0.27967091  0.09895013
  -0.36209825]
 [-0.21243545  0.03051265  0.67968776 ...  0.8766138  -0.74677826
  -0.12654438]
 ...
 [ 0.09259419  0.01600634  0.16920069 ...  0.2947813  -0.09075308
   0.26778024]
 [-0.07893512 -0.32705091  0.01177643 ...  0.12550947  0.81047316
  -0.74663095]
 [ 0.45750035  0.23448376  0.35254476 ... -0.53014229 -0.90599076
   0.55045336]]
Size:  10000
Mean:  -0.00030283210791572015
Maximum value:  1.847838244487644
Minimum value:  -2.156368013309387
Positive numbers:  5011
Negative numbers:  4989


## MODIFYING NUMPY ARRAYS

In [24]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [25]:
x = np.arange(10)
for index in range(10):
    print('Index {}: {}'.format(index, x[index]),'  ', \
          'Index {}: {}'.format(-1 - index, x[-1 - index]))  #index from end of array starting at -1

Index 0: 0    Index -1: 9
Index 1: 1    Index -2: 8
Index 2: 2    Index -3: 7
Index 3: 3    Index -4: 6
Index 4: 4    Index -5: 5
Index 5: 5    Index -6: 4
Index 6: 6    Index -7: 3
Index 7: 7    Index -8: 2
Index 8: 8    Index -9: 1
Index 9: 9    Index -10: 0


In [26]:
x = x.reshape([5, 2])
print(x)
print('\nElement in x at (3, 1) is: ', x[3, 1])

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

Element in x at (3, 1) is:  7


In [27]:
x = np.arange(10).reshape([5,2])
print(x, '\n')
x[4, 1] = 100
print(x)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] 

[[  0   1]
 [  2   3]
 [  4   5]
 [  6   7]
 [  8 100]]


In [28]:
a = np.arange(10)
b = a.reshape([5, 2])
print(a, '\n')
w = np.delete(a, [0, 4])  #delete elements 0 and 4
print(w, '\n')
print(b, '\n')
x = np.delete(b, 2, axis = 0) #delete third row of y
print(x, '\n')
y = np.delete(b, 1, axis = 1) #delete first column of y
print(y, '\n')
z = np.delete(b, [0, 4], axis = 0) #delete first and last row of y
print(z)

[0 1 2 3 4 5 6 7 8 9] 

[1 2 3 5 6 7 8 9] 

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] 

[[0 1]
 [2 3]
 [6 7]
 [8 9]] 

[[0]
 [2]
 [4]
 [6]
 [8]] 

[[2 3]
 [4 5]
 [6 7]]


### APPEND
numpy.append(array, values, axis=None)

In [29]:
a = np.arange(10)
b = a.reshape([5, 2])
print(a, '\n')

[0 1 2 3 4 5 6 7 8 9] 



In [30]:
print(a)
x = np.append(a, 10)  #append an element
print(x)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [31]:
x = np.append(a, np.arange(10, 15))
x = np.append(x, [15, 16, 17, 18, 19])
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [32]:
print(b, '\n')
y = np.append(b, [[10, 11]], axis = 0)
print(y, '\n')
z = np.append(b, [[10], [11], [12], [13], [14]], axis = 1)
print(z)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] 

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]] 

[[ 0  1 10]
 [ 2  3 11]
 [ 4  5 12]
 [ 6  7 13]
 [ 8  9 14]]


### INSERT

In [33]:
a = np.array([1, 2, 5, 6, 7])
b = np.array([[1, 2, 3], [7, 8, 9]])
print(a, '\n\n', b)

[1 2 5 6 7] 

 [[1 2 3]
 [7 8 9]]


In [34]:
x = np.insert(a, 2, [3, 4])
print(x)

[1 2 3 4 5 6 7]


In [35]:
y = np.insert(b, 1, [4, 5, 6], axis = 0)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
z = np.insert(b, 1, 5, axis = 1)  #insert a column of '5'
print(z)

[[1 5 2 3]
 [7 5 8 9]]


### HSTACK AND VSTACK
numpy.hstack(sequence_of_ndarray)<br>
numpy.vstack(sequence_of_ndarray)

In [37]:
a = np.arange(2)
b = np.arange(2, 6).reshape([2, 2])
print(a, '\n\n', b)

[0 1] 

 [[2 3]
 [4 5]]


In [38]:
x = np.vstack((a, b))
print(x)

[[0 1]
 [2 3]
 [4 5]]


In [39]:
y = np.reshape(a, [2, 1])
z = np.hstack((y, b))
print(z)

[[0 2 3]
 [1 4 5]]


## BOOLEAN INDEXING, SET OPERATIONS, SORTING

In [41]:
a = np.arange(25).reshape([5,5])
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [46]:
print('Elements greater than 10: ', a[a > 10])
print('Elements less than 10: ', a[a < 10])
print('Elements between 10 and 20: ', a[(a > 10) & (a < 20)])

Elements greater than 10:  [11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Elements less than 10:  [0 1 2 3 4 5 6 7 8 9]
Elements between 10 and 20:  [11 12 13 14 15 16 17 18 19]


In [47]:
x = a
x[(x >= 10) & (x <= 14)] = -1
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [-1 -1 -1 -1 -1]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [55]:
a = np.arange(6)
b = np.arange(4, 10)
print(a, '  ', b)
print('Elements in both a and b: ', np.intersect1d(a, b))
print('Elements in a but not b: ', np.setdiff1d(a, b))
print('All elements in a and b: ', np.union1d(a, b))

[0 1 2 3 4 5]    [4 5 6 7 8 9]
Elements in both a and b:  [4 5]
Elements in a but not b:  [0 1 2 3]
All elements in a and b:  [0 1 2 3 4 5 6 7 8 9]


In [63]:
a = np.random.randint(0, 10, size = (10,))
print('Original: ', a)
print('Sorted out of place: ', np.sort(a))
print('After sorting: ', a)
print('Unique items in a: ', np.unique(a))

Original:  [1 6 7 5 1 4 1 8 9 1]
Sorted out of place:  [1 1 1 1 4 5 6 7 8 9]
After sorting:  [1 6 7 5 1 4 1 8 9 1]
Unique items in a:  [1 4 5 6 7 8 9]


In [64]:
a = np.random.randint(0, 10, size = (10,))
print('Original: ', a)
print('After sorting: ', a)
print('Unique items in a: ', np.unique(a))

Original:  [6 5 3 5 7 1 4 4 2 6]
After sorting:  [6 5 3 5 7 1 4 4 2 6]
Unique items in a:  [1 2 3 4 5 6 7]


### NUMPY SORT
numpy.sort(array, axis=-1, kind=None, order=None)

[[4 9 9 9 0]
 [4 1 6 3 2]
 [4 3 7 0 7]
 [9 8 1 1 9]
 [5 3 2 5 4]]


In [72]:
a = np.random.randint(0, 10, size = (5,5))
print('Original:\n', a)
print()
print('Sorted Columns:\n', np.sort(a, axis = 0))
print()
print('Sorted Rows:\n', np.sort(a, axis = 1))

Original:
 [[8 5 6 5 5]
 [7 6 8 3 3]
 [2 9 4 5 9]
 [7 7 7 5 7]
 [5 4 9 6 7]]

Sorted Columns:
 [[2 4 4 3 3]
 [5 5 6 5 5]
 [7 6 7 5 7]
 [7 7 8 5 7]
 [8 9 9 6 9]]

Sorted Rows:
 [[5 5 5 6 8]
 [3 3 6 7 8]
 [2 4 5 9 9]
 [5 7 7 7 7]
 [4 5 6 7 9]]
