# NUMPY ARRAYS
## CREATING NUMPY ARRAYS

In [1]:
import numpy as np

In [2]:
x = np.array([0, 1, 2, 3, 4])
print('x: ', x)
print('x dimensions: ', x.ndim)
print('x type: ', type(x))
print('x element types: ', x.dtype)

x:  [0 1 2 3 4]
x dimensions:  1
x type:  <class 'numpy.ndarray'>
x element types:  int32


In [3]:
y = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
print('y:\n', y)
print('y dimensions: ', y.ndim)
print('y shape: ', y.shape)
print('y has a total of ', y.size, ' elements')
print('y type: ', type(y))
print('y element types: ', y.dtype)

y:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
y dimensions:  2
y shape:  (4, 3)
y has a total of  12  elements
y type:  <class 'numpy.ndarray'>
y element types:  int32


Create array specifying the datatype (dtype) of the elements

In [4]:
x = np.array([0, 1, 2, 3, 4], dtype = np.float64)
print('x: ', x)
print('The elements in x are of type: ', x.dtype)

x:  [0. 1. 2. 3. 4.]
The elements in x are of type:  float64


Save a NumPy array to a file.

In [5]:
np.save('my_array', y)

Load saved array from current directory

In [6]:
z = np.load('my_array.npy')
print('\nz =\n', z, '\n')
print('z is an object of type: ', type(z))
print('The elements in z are type: ', z.dtype)


z =
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

z is an object of type:  <class 'numpy.ndarray'>
The elements in z are type:  int32


## MULTI-DIMENSIONAL ARRAYS IN NUMPY
Indexing arrays in numpy [NUM_ROWS][NUM_COLUMNS]<br>
Axis 0 is columns, Axis 1 is rows

In [7]:
a = np.zeros((3,4))
print('a =\n', a)
print('a has shape: ', a.shape)
print('a is an object of type:', type(x))
print('The elements in a are of type:', a.dtype)

a =
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
a has shape:  (3, 4)
a is an object of type: <class 'numpy.ndarray'>
The elements in a are of type: float64


In [8]:
a = np.ones((5,2), dtype = np.int64)
print('a =\n', a)
print('a has shape: ', a.shape)
print('a is an object of type:', type(x))
print('The elements in a are of type:', a.dtype)

a =
 [[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
a has shape:  (5, 2)
a is an object of type: <class 'numpy.ndarray'>
The elements in a are of type: int64


In [9]:
a = np.full((2,3), 10)
print('a =\n', a)
print('a has shape: ', a.shape)
print('a is an object of type:', type(x))
print('The elements in a are of type:', a.dtype)

a =
 [[10 10 10]
 [10 10 10]]
a has shape:  (2, 3)
a is an object of type: <class 'numpy.ndarray'>
The elements in a are of type: int32


In [10]:
a = np.eye(7)
print('a =\n', a)
print('a has shape: ', a.shape)
print('a is an object of type:', type(x))
print('The elements in a are of type:', a.dtype)

a =
 [[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
a has shape:  (7, 7)
a is an object of type: <class 'numpy.ndarray'>
The elements in a are of type: float64


In [11]:
a = np.diag([0, 1, 2, 3, 4])
print('a =\n', a)
print('a has shape: ', a.shape)
print('a is an object of type:', type(x))
print('The elements in a are of type:', a.dtype)

a =
 [[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]]
a has shape:  (5, 5)
a is an object of type: <class 'numpy.ndarray'>
The elements in a are of type: int32


### ARANGE
numpy.arange([start, ]stop, [step, ]dtype=None)

In [12]:
a = np.arange(10)
print('a =\n', a)
print('a has shape: ', a.shape)
print('a is an object of type:', type(x))
print('The elements in a are of type:', a.dtype)

a =
 [0 1 2 3 4 5 6 7 8 9]
a has shape:  (10,)
a is an object of type: <class 'numpy.ndarray'>
The elements in a are of type: int32


In [13]:
a = np.arange(1, 9)
print('a =\n', a)
print('a has shape: ', a.shape)
print('a is an object of type:', type(x))
print('The elements in a are of type:', a.dtype)

a =
 [1 2 3 4 5 6 7 8]
a has shape:  (8,)
a is an object of type: <class 'numpy.ndarray'>
The elements in a are of type: int32


In [14]:
a = np.arange(1, 14, 3)
print('a =\n', a)
print('a has shape: ', a.shape)
print('a is an object of type:', type(x))
print('The elements in a are of type:', a.dtype)

a =
 [ 1  4  7 10 13]
a has shape:  (5,)
a is an object of type: <class 'numpy.ndarray'>
The elements in a are of type: int32


### LINSPACE
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

In [15]:
a = np.linspace(0, 25, 10)
print('a =\n', a)
print('a has shape: ', a.shape)
print('a is an object of type:', type(x))
print('The elements in a are of type:', a.dtype)

a =
 [ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]
a has shape:  (10,)
a is an object of type: <class 'numpy.ndarray'>
The elements in a are of type: float64


In [16]:
a = np.linspace(0, 25, 10, endpoint = False)
print('a =\n', a)
print('a has shape: ', a.shape)
print('a is an object of type:', type(x))
print('The elements in a are of type:', a.dtype)

a =
 [ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]
a has shape:  (10,)
a is an object of type: <class 'numpy.ndarray'>
The elements in a are of type: float64


### RESHAPE
numpy.reshape(array, newshape, order='C')[source]

In [17]:
a = np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [18]:
a = np.reshape(a, [4,5])
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [19]:
a = np.reshape(a, [10, 2])
print(a)
print('a has shape: ', a.shape)
print('a is an object of type:', type(x))
print('The elements in a are of type:', a.dtype)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
a has shape:  (10, 2)
a is an object of type: <class 'numpy.ndarray'>
The elements in a are of type: int32


In [20]:
a = np.diag(np.arange(0, 10, 2))
print(a)

[[0 0 0 0 0]
 [0 2 0 0 0]
 [0 0 4 0 0]
 [0 0 0 6 0]
 [0 0 0 0 8]]


## NUMPY RANDOM FUNCTIONS

In [21]:
a = np.random.random((4, 6))
print(a)

[[0.09185817 0.03745655 0.71341762 0.39649741 0.64575452 0.19478731]
 [0.86929593 0.19036257 0.765738   0.10858729 0.02038501 0.18491185]
 [0.48343928 0.28225053 0.21522634 0.27385871 0.53078935 0.37796014]
 [0.38788967 0.88612379 0.63460884 0.08177094 0.53131373 0.36964273]]


In [22]:
a = np.random.randint(1, 9, size=(2, 10))
print(a)

[[8 2 2 2 6 7 3 5 5 6]
 [6 4 2 6 1 1 5 1 7 3]]


In [23]:
a = np.random.normal(0, .5, size = (100, 100))
print(a)
print('Size: ', a.size)
print('Mean: ', a.mean())
print('Maximum value: ', a.max())
print('Minimum value: ', a.min())
print('Positive numbers: ', (a > 0).sum())
print('Negative numbers: ', (a < 0).sum())

[[-0.12804761  0.18639495  0.1705707  ...  0.5672867  -0.49467641
   0.30431981]
 [ 0.58087901  0.55342523 -0.00304509 ...  0.01491253  0.73017614
  -0.83854076]
 [-0.03938273  0.23379586 -0.50513369 ... -0.55735157 -0.31397126
   0.07609401]
 ...
 [-0.1741635  -0.33376321 -0.01482697 ...  0.4091355  -0.2232288
  -0.08295528]
 [-0.09581066 -0.03764567 -0.37923269 ...  0.46636349 -0.0825266
  -0.00328703]
 [ 0.43223717  0.40620143  1.08420461 ... -0.65495243 -0.31188941
   0.76811656]]
Size:  10000
Mean:  -0.002540440538038735
Maximum value:  1.9031090999693898
Minimum value:  -1.9522209300393625
Positive numbers:  5020
Negative numbers:  4980


## MODIFYING NUMPY ARRAYS

In [24]:
x = np.arange(10)
print(x)

[0 1 2 3 4 5 6 7 8 9]


In [25]:
x = np.arange(10)
for index in range(10):
    print('Index {}: {}'.format(index, x[index]),'  ', \
          'Index {}: {}'.format(-1 - index, x[-1 - index]))  #index from end of array starting at -1

Index 0: 0    Index -1: 9
Index 1: 1    Index -2: 8
Index 2: 2    Index -3: 7
Index 3: 3    Index -4: 6
Index 4: 4    Index -5: 5
Index 5: 5    Index -6: 4
Index 6: 6    Index -7: 3
Index 7: 7    Index -8: 2
Index 8: 8    Index -9: 1
Index 9: 9    Index -10: 0


In [26]:
x = x.reshape([5, 2])
print(x)
print('\nElement in x at (3, 1) is: ', x[3, 1])

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]]

Element in x at (3, 1) is:  7


In [27]:
x = np.arange(10).reshape([5,2])
print(x, '\n')
x[4, 1] = 100
print(x)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] 

[[  0   1]
 [  2   3]
 [  4   5]
 [  6   7]
 [  8 100]]


In [28]:
a = np.arange(10)
b = a.reshape([5, 2])
print(a, '\n')
w = np.delete(a, [0, 4])  #delete elements 0 and 4
print(w, '\n')
print(b, '\n')
x = np.delete(b, 2, axis = 0) #delete third row of y
print(x, '\n')
y = np.delete(b, 1, axis = 1) #delete first column of y
print(y, '\n')
z = np.delete(b, [0, 4], axis = 0) #delete first and last row of y
print(z)

[0 1 2 3 4 5 6 7 8 9] 

[1 2 3 5 6 7 8 9] 

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] 

[[0 1]
 [2 3]
 [6 7]
 [8 9]] 

[[0]
 [2]
 [4]
 [6]
 [8]] 

[[2 3]
 [4 5]
 [6 7]]


### APPEND
numpy.append(array, values, axis=None)

In [29]:
a = np.arange(10)
b = a.reshape([5, 2])
print(a, '\n')

[0 1 2 3 4 5 6 7 8 9] 



In [30]:
print(a)
x = np.append(a, 10)  #append an element
print(x)

[0 1 2 3 4 5 6 7 8 9]
[ 0  1  2  3  4  5  6  7  8  9 10]


In [31]:
x = np.append(a, np.arange(10, 15))
x = np.append(x, [15, 16, 17, 18, 19])
print(x)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [32]:
print(b, '\n')
y = np.append(b, [[10, 11]], axis = 0)
print(y, '\n')
z = np.append(b, [[10], [11], [12], [13], [14]], axis = 1)
print(z)

[[0 1]
 [2 3]
 [4 5]
 [6 7]
 [8 9]] 

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]] 

[[ 0  1 10]
 [ 2  3 11]
 [ 4  5 12]
 [ 6  7 13]
 [ 8  9 14]]


### INSERT

In [33]:
a = np.array([1, 2, 5, 6, 7])
b = np.array([[1, 2, 3], [7, 8, 9]])
print(a, '\n\n', b)

[1 2 5 6 7] 

 [[1 2 3]
 [7 8 9]]


In [34]:
x = np.insert(a, 2, [3, 4])
print(x)

[1 2 3 4 5 6 7]


In [35]:
y = np.insert(b, 1, [4, 5, 6], axis = 0)
print(y)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [36]:
z = np.insert(b, 1, 5, axis = 1)  #insert a column of '5'
print(z)

[[1 5 2 3]
 [7 5 8 9]]


### HSTACK AND VSTACK
numpy.hstack(sequence_of_ndarray)<br>
numpy.vstack(sequence_of_ndarray)

In [37]:
a = np.arange(2)
b = np.arange(2, 6).reshape([2, 2])
print(a, '\n\n', b)

[0 1] 

 [[2 3]
 [4 5]]


In [38]:
x = np.vstack((a, b))
print(x)

[[0 1]
 [2 3]
 [4 5]]


In [39]:
y = np.reshape(a, [2, 1])
z = np.hstack((y, b))
print(z)

[[0 2 3]
 [1 4 5]]


## BOOLEAN INDEXING, SET OPERATIONS, SORTING

In [40]:
a = np.arange(25).reshape([5,5])
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [41]:
print('Elements greater than 10: ', a[a > 10])
print('Elements less than 10: ', a[a < 10])
print('Elements between 10 and 20: ', a[(a > 10) & (a < 20)])

Elements greater than 10:  [11 12 13 14 15 16 17 18 19 20 21 22 23 24]
Elements less than 10:  [0 1 2 3 4 5 6 7 8 9]
Elements between 10 and 20:  [11 12 13 14 15 16 17 18 19]


In [42]:
x = a
x[(x >= 10) & (x <= 14)] = -1
print(x)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [-1 -1 -1 -1 -1]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [43]:
a = np.arange(6)
b = np.arange(4, 10)
print(a, '  ', b)
print('Elements in both a and b: ', np.intersect1d(a, b))
print('Elements in a but not b: ', np.setdiff1d(a, b))
print('All elements in a and b: ', np.union1d(a, b))

[0 1 2 3 4 5]    [4 5 6 7 8 9]
Elements in both a and b:  [4 5]
Elements in a but not b:  [0 1 2 3]
All elements in a and b:  [0 1 2 3 4 5 6 7 8 9]


In [44]:
a = np.random.randint(0, 10, size = (10,))
print('Original: ', a)
print('Sorted out of place: ', np.sort(a))
print('After sorting: ', a)
print('Unique items in a: ', np.unique(a))

Original:  [1 9 3 0 7 0 9 3 4 4]
Sorted out of place:  [0 0 1 3 3 4 4 7 9 9]
After sorting:  [1 9 3 0 7 0 9 3 4 4]
Unique items in a:  [0 1 3 4 7 9]


In [45]:
a = np.random.randint(0, 10, size = (10,))
print('Original: ', a)
print('After sorting: ', a)
print('Unique items in a: ', np.unique(a))

Original:  [7 5 2 9 5 7 6 3 5 5]
After sorting:  [7 5 2 9 5 7 6 3 5 5]
Unique items in a:  [2 3 5 6 7 9]


### NUMPY SORT
numpy.sort(array, axis=-1, kind=None, order=None)

In [46]:
a = np.random.randint(0, 10, size = (5,5))
print('Original:\n', a)
print()
print('Sorted Columns:\n', np.sort(a, axis = 0))
print()
print('Sorted Rows:\n', np.sort(a, axis = 1))

Original:
 [[1 1 6 1 5]
 [5 1 5 4 6]
 [5 1 6 4 7]
 [9 0 3 0 0]
 [8 6 3 3 1]]

Sorted Columns:
 [[1 0 3 0 0]
 [5 1 3 1 1]
 [5 1 5 3 5]
 [8 1 6 4 6]
 [9 6 6 4 7]]

Sorted Rows:
 [[1 1 1 5 6]
 [1 4 5 5 6]
 [1 4 5 6 7]
 [0 0 0 3 9]
 [1 3 3 6 8]]


## ARITHMETIC OPERATIONS ON ARRAYS AND BROADCASTING

In [50]:
a = np.array([0, 1 , 2, 3])
b = np.array([5.5, 6.5, 7.5, 8.5])
print('a: ', a)
print('b: ', b)

a:  [0 1 2 3]
b:  [5.5 6.5 7.5 8.5]


In [52]:
print(a + b)
print(np.add(a, b))

[ 5.5  7.5  9.5 11.5]
[ 5.5  7.5  9.5 11.5]


In [53]:
print(a - b)
print(np.subtract(a, b))

[-5.5 -5.5 -5.5 -5.5]
[-5.5 -5.5 -5.5 -5.5]


In [54]:
print(a * b)
print(np.multiply(a, b))

[ 0.   6.5 15.  25.5]
[ 0.   6.5 15.  25.5]


In [55]:
print(a / b)
print(np.divide(a, b))

[0.         0.15384615 0.26666667 0.35294118]
[0.         0.15384615 0.26666667 0.35294118]


In [57]:
x = a.reshape([2, 2])
print(x)

[[0 1]
 [2 3]]


In [60]:
print(x + x)
print()
print(x - x)
print()
print(x * x)
#print(x / x)

[[0 2]
 [4 6]]

[[0 0]
 [0 0]]

[[0 1]
 [4 9]]


In [62]:
a = np.arange(5)
print('a = ', a)
print('EXP(a) = ', np.exp(a))
print('SQRT(a) = ', np.sqrt(2))
print('POW(a, 2) = ', np.power(a, 2))

a =  [0 1 2 3 4]
EXP(a) =  [ 1.          2.71828183  7.3890561  20.08553692 54.59815003]
SQRT(a) =  1.4142135623730951
POW(a, 2) =  [ 0  1  4  9 16]


### STATISTICAL FUNCTIONS
mean, sum, std, median, max, min

In [63]:
a = np.arange(1, 5).reshape([2,2])
print(a)

[[1 2]
 [3 4]]


In [66]:
print('Average of all elements:\n', np.mean(a))
print('Average of all elements by column:\n', np.mean(a, axis = 0))
print('Average of all elements by row:\n', np.mean(a, axis = 1))

Average of all elements:
 2.5
Average of all elements by column:
 [2. 3.]
Average of all elements by row:
 [1.5 3.5]


### CHANGE VALUE OF ALL ARRAY ELEMENTS

In [68]:
a = np.arange(1, 5).reshape([2,2])
print(a)
print()
print(3 * a)

[[1 2]
 [3 4]]

[[ 3  6]
 [ 9 12]]


In [70]:
a = np.arange(1, 10).reshape([3,3])
b = np.arange(1, 4)
c = np.arange(1, 4).reshape([3, 1])
print(a)
print()
print(b)
print()
print(c)

[[1 2 3]
 [4 5 6]
 [7 8 9]]

[1 2 3]

[[1]
 [2]
 [3]]


In [72]:
print('a + b:\n', a + b)

a + b:
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]


In [73]:
print('a + c:\n', a + c)

a + c:
 [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]
