### NUMPY BASICS

In [2]:
import numpy as np

In [3]:
x = np.array([0, 1, 2, 3, 4])
print('x: ', x)
print('x dimensions: ', x.ndim)
print('x type: ', type(x))
print('x element types: ', x.dtype)

x:  [0 1 2 3 4]
x dimensions:  1
x type:  <class 'numpy.ndarray'>
x element types:  int32


In [4]:
y = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
print('y:\n', y)
print('y dimensions: ', y.ndim)
print('y shape: ', y.shape)
print('y has a total of ', y.size, ' elements')
print('y type: ', type(y))
print('y element types: ', y.dtype)

y:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
y dimensions:  2
y shape:  (4, 3)
y has a total of  12  elements
y type:  <class 'numpy.ndarray'>
y element types:  int32


Create array specifying the datatype (dtype) of the elements

In [5]:
x = np.array([0, 1, 2, 3, 4], dtype = np.float64)
print('x: ', x)
print('The elements in x are of type: ', x.dtype)

x:  [0. 1. 2. 3. 4.]
The elements in x are of type:  float64


Save a NumPy array to a file.

In [6]:
np.save('my_array', y)

Load saved array from current directory

In [7]:
z = np.load('my_array.npy')
print('\nz =\n', z, '\n')
print('z is an object of type: ', type(z))
print('The elements in z are type: ', z.dtype)


z =
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

z is an object of type:  <class 'numpy.ndarray'>
The elements in z are type:  int32


### MULTI-DIMENSIONAL ARRAYS IN NUMPY
Indexing arrays in numpy [NUM_ROWS][NUM_COLUMNS]

In [16]:
a = np.zeros((3,4))
print('a =\n', a)
print('a has shape: ', a.shape)
print('a is an object of type:', type(x))
print('The elements in a are of type:', a.dtype)

a =
 [[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
a has shape:  (3, 4)
a is an object of type: <class 'numpy.ndarray'>
The elements in a are of type: float64


In [19]:
a = np.ones((5,2), dtype = np.int64)
print('a =\n', a)
print('a has shape: ', a.shape)
print('a is an object of type:', type(x))
print('The elements in a are of type:', a.dtype)

a =
 [[1 1]
 [1 1]
 [1 1]
 [1 1]
 [1 1]]
a has shape:  (5, 2)
a is an object of type: <class 'numpy.ndarray'>
The elements in a are of type: int64


In [20]:
a = np.full((2,3), 10)
print('a =\n', a)
print('a has shape: ', a.shape)
print('a is an object of type:', type(x))
print('The elements in a are of type:', a.dtype)

a =
 [[10 10 10]
 [10 10 10]]
a has shape:  (2, 3)
a is an object of type: <class 'numpy.ndarray'>
The elements in a are of type: int32


In [21]:
a = np.eye(7)
print('a =\n', a)
print('a has shape: ', a.shape)
print('a is an object of type:', type(x))
print('The elements in a are of type:', a.dtype)

a =
 [[1. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 1. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 0. 0. 1.]]
a has shape:  (7, 7)
a is an object of type: <class 'numpy.ndarray'>
The elements in a are of type: float64


In [22]:
a = np.diag([0, 1, 2, 3, 4])
print('a =\n', a)
print('a has shape: ', a.shape)
print('a is an object of type:', type(x))
print('The elements in a are of type:', a.dtype)

a =
 [[0 0 0 0 0]
 [0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]]
a has shape:  (5, 5)
a is an object of type: <class 'numpy.ndarray'>
The elements in a are of type: int32


### ARANGE
numpy.arange([start, ]stop, [step, ]dtype=None)

In [24]:
a = np.arange(10)
print('a =\n', a)
print('a has shape: ', a.shape)
print('a is an object of type:', type(x))
print('The elements in a are of type:', a.dtype)

a =
 [0 1 2 3 4 5 6 7 8 9]
a has shape:  (10,)
a is an object of type: <class 'numpy.ndarray'>
The elements in a are of type: int32


In [25]:
a = np.arange(1, 9)
print('a =\n', a)
print('a has shape: ', a.shape)
print('a is an object of type:', type(x))
print('The elements in a are of type:', a.dtype)

a =
 [1 2 3 4 5 6 7 8]
a has shape:  (8,)
a is an object of type: <class 'numpy.ndarray'>
The elements in a are of type: int32


In [26]:
a = np.arange(1, 14, 3)
print('a =\n', a)
print('a has shape: ', a.shape)
print('a is an object of type:', type(x))
print('The elements in a are of type:', a.dtype)

a =
 [ 1  4  7 10 13]
a has shape:  (5,)
a is an object of type: <class 'numpy.ndarray'>
The elements in a are of type: int32


### LINSPACE
numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

In [28]:
a = np.linspace(0, 25, 10)
print('a =\n', a)
print('a has shape: ', a.shape)
print('a is an object of type:', type(x))
print('The elements in a are of type:', a.dtype)

a =
 [ 0.          2.77777778  5.55555556  8.33333333 11.11111111 13.88888889
 16.66666667 19.44444444 22.22222222 25.        ]
a has shape:  (10,)
a is an object of type: <class 'numpy.ndarray'>
The elements in a are of type: float64


In [29]:
a = np.linspace(0, 25, 10, endpoint = False)
print('a =\n', a)
print('a has shape: ', a.shape)
print('a is an object of type:', type(x))
print('The elements in a are of type:', a.dtype)

a =
 [ 0.   2.5  5.   7.5 10.  12.5 15.  17.5 20.  22.5]
a has shape:  (10,)
a is an object of type: <class 'numpy.ndarray'>
The elements in a are of type: float64


### RESHAPE
numpy.reshape(array, newshape, order='C')[source]

In [30]:
a = np.arange(20)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [32]:
a = np.reshape(a, [4,5])
print(a)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]]


In [34]:
a = np.reshape(a, [10, 2])
print(a)
print('a has shape: ', a.shape)
print('a is an object of type:', type(x))
print('The elements in a are of type:', a.dtype)

[[ 0  1]
 [ 2  3]
 [ 4  5]
 [ 6  7]
 [ 8  9]
 [10 11]
 [12 13]
 [14 15]
 [16 17]
 [18 19]]
a has shape:  (10, 2)
a is an object of type: <class 'numpy.ndarray'>
The elements in a are of type: int32


In [37]:
a = np.diag(np.arange(0, 10, 2))
print(a)

[[0 0 0 0 0]
 [0 2 0 0 0]
 [0 0 4 0 0]
 [0 0 0 6 0]
 [0 0 0 0 8]]


### NUMPY RANDOM FUNCTIONS

In [39]:
a = np.random.random((4, 6))
print(a)

[[0.29209074 0.50871176 0.83472431 0.901799   0.71623433 0.53223911]
 [0.35499908 0.18773567 0.77904673 0.36905441 0.77553461 0.13793199]
 [0.30595264 0.58481978 0.77539154 0.65264916 0.43151194 0.48064779]
 [0.34109382 0.31131296 0.00278631 0.92875234 0.42685454 0.06384759]]


In [40]:
a = np.random.randint(1, 9, size=(2, 10))
print(a)

[[6 2 7 2 5 8 7 4 5 2]
 [6 6 5 4 3 4 3 6 6 1]]


In [45]:
a = np.random.normal(0, .5, size = (100, 100))
print(a)
print('Size: ', a.size)
print('Mean: ', a.mean())
print('Maximum value: ', a.max())
print('Minimum value: ', a.min())
print('Positive numbers: ', (a > 0).sum())
print('Negative numbers: ', (a < 0).sum())

[[ 0.13928167 -0.19579643  0.61656231 ...  0.21874742  0.54899173
   0.71265308]
 [ 1.25321585  0.05985776 -0.26652487 ... -0.07203501 -0.62395191
   0.5121138 ]
 [ 0.23036111  0.08717425 -0.44319963 ...  0.40719962 -0.32818732
  -0.08023412]
 ...
 [-0.25312007  0.48077573 -0.04185594 ...  0.2102754   0.07552488
  -0.24564416]
 [-0.49866477  0.71258124  0.37843627 ...  0.53461277  0.87266625
  -0.16974612]
 [-0.40936582 -0.21064339  0.14135052 ... -0.8335794  -0.91331635
   0.57258004]]
Size:  10000
Mean:  -0.0008490933051549515
Maximum value:  1.817920823736869
Minimum value:  -1.8101200208030397
Positive numbers:  4997
Negative numbers:  5003
