In [1]:
import numpy as nd

In [13]:
x = nd.array([0, 1, 2, 3, 4])
print('x:\n', x)
print('x dimensions: ', x.ndim)
print('x type: ', type(x))
print('x element types: ', x.dtype)

x:
 [0 1 2 3 4]
x dimensions:  1
x type:  <class 'numpy.ndarray'>
x element types:  int32


In [14]:
y = nd.array([[0, 1, 2], [3, 4, 5], [6, 7, 8], [9, 10, 11]])
print('y:\n', y)
print('y dimensions: ', y.ndim)
print('y type: ', type(y))
print('y element types: ', y.dtype)

y:
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
y dimensions:  2
y type:  <class 'numpy.ndarray'>
y element types:  int32
